services:
  # Frontend Service
  front-user:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_TARGET: user
    environment:
      VITE_GATEWAY_URL: gateway-service
      VITE_GATEWAY_PORT: 19080
    ports:
      - "14001:4001"
    container_name: frontend-user
  front-admin:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_TARGET: admin
    environment:
      VITE_GATEWAY_URL: gateway-service
      VITE_GATEWAY_PORT: 19080
    ports:
      - "14002:4002"
    container_name: frontend-admin 

networks:
  frontend-network:
    driver: bridge